#!/usr/bin/env python
# encoding: utf-8

import sys
import os
import unittest
from hsh.library.hash import Hasher

class HasherClassTest(unittest.TestCase):

    def setUp(self):
        self.testfile1_path = "testdir1/hashtest.txt"
        self.testfile2_path = "testdir1/hashtest-mod.txt"
        self.hashtest_md5_hash = "e1eadba7c29a7c251073da9de91a08c0"
        self.hashtest_sha1_hash = "e5dd269504b4400ee18d723077d9de761695699e"
        self.hashtest_sha224_hash = "22ad9b21f5f46d7734a2562f45d3ad598914976798aed542195859b8"
        self.hashtest_sha256_hash = "beed7da44e4597faa81ffea24ba508efaf25d9df75019fec37b4d673174c5757"
        self.hashtest_sha384_hash = "e31fdb3c9913879c7ef5848df430da0889c710add335e09ed4939a6229c1a188fa486efe8ec7f50b4da396edb59cf683"
        self.hashtest_sha512_hash = "e9ccee5c828cf89ea44f33ea633c73cde4d4d5e28c1084eabed5d04414029e13f9523dd1a616fa3d1cd90b92d068d1a6ff23a326916c07751d15d7c46a680bd4"

    def tearDown(self):
        pass

    #------------------------------------------------------------------------------
    # Hash Digest Accuracy Tests
    #   compare to hash digests generated by shasum and md5 applications (MacOSX) for the hashtest.txt file
    #------------------------------------------------------------------------------
    def test_md5_vs_standard(self):
        h = Hasher()
        hd = h.md5(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_md5_hash)

    def test_sha1_vs_standard(self):
        h = Hasher()
        hd = h.sha1(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_sha1_hash)

    def test_sha224_vs_standard(self):
        h = Hasher()
        hd = h.sha224(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_sha224_hash)

    def test_sha256_vs_standard(self):
        h = Hasher()
        hd = h.sha256(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_sha256_hash)

    def test_sha384_vs_standard(self):
        h = Hasher()
        hd = h.sha384(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_sha384_hash)

    def test_sha512_vs_standard(self):
        h = Hasher()
        hd = h.sha512(self.testfile1_path)
        self.assertEqual(hd, self.hashtest_sha512_hash)


